### ISSUE TITLE
Found more documentation

### ISSUE THREAD

**Issue by zZeck** [chaoticgd/ccc#136]
I don't see this one in your list, maybe it is useful to you.
I been scrounging around trying to fix issues with mdebug format in GDB and ran into this.

Found [this](https://gcc.gnu.org/legacy-ml/gcc-patches/1999-01/msg00241.html) old gcc issue mentioning a "Object File/Symbol Table Format Specification for Digital UNIX V5.0". The link for the document is dead, and nothing useful is on the way back machine either, redirects from the DEC site, to compaq, which also has nothing. However I believe [this](http://www2.phys.canterbury.ac.nz/dept/docs/manuals/unix/DEC_5.0a_Docs/ACRO_SUP/OBJSPEC.PDF) is the same document. The internet archive has a [slightly newer version](https://ia800501.us.archive.org/6/items/tru64coff/tru64coff.pdf) of it, but it has less pages. Did not investigate why, could just be formatting. Chapter 5 on the symbol table, and explains more about this format than I've seen anywhere else. Chapter 9 is a bunch of example programs, followed by their mdebug dump information from a tool like stdump.

**Comment by chaoticgd** [comment]
Nice find! I'll probably add it to the list in a bit.

The binary stuff all looks accurate, just based on a quick skim, although GCC does leave a lot of the fields in for example the procedure descriptors empty. The symbol table examples themselves look a bit different to what GCC outputs. For example I don't recognize how they're handling inheritance, the way GCC does it may be a GNU extension.

**Comment by chaoticgd** [comment]
I seem to remember the entire auxiliary symbol table section isn't written out by GCC either.

**Comment by chaoticgd** [comment]
I've added the files.
