### ISSUE TITLE
Suggestion: Splitting into .s files?

### ISSUE THREAD

**Issue by OndrikB** [chaoticgd/ccc#139]
Would it be possible to have something similar to `uncc` but simply splitting the ELF into assembly files? It would be very helpful for decompilation projects so that the ELF can be built from them. This way, a project can also continuously verify that their code matches the original perfectly.

**Comment by chaoticgd** [comment]
It would be a great feature, although I'm currently working on something else.

**Comment by chaoticgd** [comment]
Another solution would be to implement code diffing for individual object files, but in the end it would be nice to have both.
